name: interop

on:
  push:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_PASSWORD }}
    - name: Build and publish interop docker image
      uses: docker/build-push-action@v2
      with:
        context: interop
        file: interop/Dockerfile
        push: true
        tags: ghcr.io/ngtcp2/ngtcp2-interop:latest
